### PR TITLE
Adds a way to force push from the Graph

### PR DESCRIPTION
**Pull request by nzaytsev**
# Description

- add split button dropdown in case of both ahead and behind changes appeared

Screenshot 2024-09-04 at 14 58 43

Screenshot 2024-09-04 at 14 58 50

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [x] My changes include any required corresponding changes to the documentation (including CHANGELOG.md and README.md)
- [ ] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

**Comment by nzaytsev** [comment]
@d13 @eamodio @sergeibbb 
Check this behavior, I suggested the sync button that is similar to default VSCode button. It appears only when the branch is both ahead and behind and suggests pulling with options, then awaits and suggests pushing with available options. Also it contains the split button dropdown with 3 options: sync, pull and push

**Comment by d13** [comment]
> @d13 @eamodio @sergeibbb Check this behavior, I suggested the sync button that is similar to default VSCode button. It appears only when the branch is both ahead and behind and suggests pulling with options, then awaits and suggests pushing with available options. Also it contains the split button dropdown with 3 options: sync, pull and push

Let's wait on the sync action and focus on the push, pull and force-push. Sync will need some more thought on how we offer that, both on the Graph and throughout GitLens.

**Review by d13 — COMMENTED** [review]
In general, we want to avoid using React as much as possible in GitLens. 

For history, when the graph view was originally built, we didn't have a grasp on how to effectively use web components yet. 

Our plan now is to invert how React is used today in the graph view. Instead of creating React wrappers for every web component used in the Graph, we plan to put a single web component wrapper around the graph's react component and focus on using web platform APIs for reactivity.

**Comment by nzaytsev** [comment]
removed/hidden code associated with sync function, use only pull and push

@d13 

> In general, we want to avoid using React as much as possible in GitLens.

Do you suggest moving the SyncButton component to lit now?

**Review by eamodio — APPROVED** [review]
Looks good, just pushed an enhancement to the tooltip

**Pull request merged**
