### PR TITLE
Fixes #1968, #1027 - Fetch-> fatal: could not read Username

### LINKED ISSUE #1968: Unable to fetch repository. See output channel for more details
I'm getting this output when clicking `fetch` in `remotes` in `source control`: 

`Unable to fetch repository. See output channel for more details`

```
[2022-04-15 14:41:40.931] [ xxxx] LocalGitProvider.fetch — failed • 347 ms
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin BRANCH_NAME
fatal: could not read Username for 'https://github.com': No such device or address

[2022-04-15 14:41:40.931] [ xxxx] GitProviderService.fetch — failed • 347 ms
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin BRANCH_NAME
fatal: could not read Username for 'https://github.com': No such device or address

[2022-04-15 14:41:40.931] /home/username/.vscode/extensions/eamodio.gitlens-12.0.6/dist/gitlens.js:36:7507
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin BRANCH_NAME
fatal: could not read Username for 'https://github.com': No such device or address
```

- GitLens Version: 12.0.6
- Git Version: 2.25.1
- VSCode Version: 1.66.2
- OS Version: Ubuntu 20.04

If I press Ctrl-Shift-P and use native Fetch there, it works (but not `fetch` by GitLens). Also push and pull in VScode itself works (not sure how to test it with GitLens). Also switching to another branch in `remotes` works. 

I'm signed in with GitHub in VSCode.

### PR DESCRIPTION
**Pull request by foxwoods369**
# Description

Uses the core git fetch command instead of a command-line git fetch so VsCode will prompt the user for their username and password. Pull & push also use their corresponding core commands.

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [x] My changes include any required corresponding changes to the documentation (including CHANGELOG.md and README.md)
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

**Review by d13 — APPROVED** [review]
Thanks for contributing @foxwoods369! Looks good to me 🎉

**Comment by Weijiang-Xiong** [comment]
Hello, I'm now having the error again, same as #1027. 

I'm sshing to an ubuntu 22.04 remote compute from an windows 10 PC, and I signed in to github in vscode. The builtin source control works fine, but the branch fetching in gitlens panel gives the following error. However, when I click the globe button to open remote branch, it also opens the correct branch in my browser. 

Here is the output by gitlens. 

> [2023-06-24 23:11:39.156] /home/admin/.vscode-server/extensions/eamodio.gitlens-14.0.1/dist/gitlens.js:1:296036
> Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin engine:refs/remotes/origin/engine
> fatal: could not read Username for 'https://github.com': No such device or address

Here is the version info from vscode. 

> Version: 1.79.2 (user setup)
> Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
> Date: 2023-06-14T08:57:04.379Z
> Electron: 22.5.7
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.19045

**Comment by axosoft-ramint** [comment]
@Weijiang-Xiong I would like your help to test a potential fix to your issue.

Currently, when using a fetch without a branch specified, we use the built-in SCM's version of fetch. When a branch is specified for the fetch, we use our own, which is why you would be getting the error output there and not in other fetch cases.

We are trying to determine if this is because of the difference between the SCM's auth for git operations and our own.

In tomorrow's pre-release of GitLens, we've introduced an experimental option where we pull in some of the Git environment of the SCM into our own Git implementation.

We would like your help to test the branch fetch that is failing for you above by doing the following:

1. Update to the Pre-release version of GitLens (once the latest one releases tomorrow), which should be 8 hours or so from this post. You can switch to the Pre-release version of GitLens from its extension banner on the GitLens extension homepage (from the Extensions view).

image

2. In your settings JSON, add the following line: `"gitlens.experimental.nativeGit": true`. You can modify by Command Palette command: `Preferences: Open User Settings (JSON)`

image

image

3. Reload using the Developer: Reload Window` command from the Command Palette or just reset VS Code (so that the new setting you added takes effect).

image

4. Try the branch fetch again, as you did above.
5. Let me know if it works or if you get similar error output.

**Comment by Weijiang-Xiong** [comment]
Thank you @axosoft-ramint ! I switched to the pre-release, and added the setting as you said, and now I can refresh the branches without problem!

**Comment by axosoft-ramint** [comment]
@Weijiang-Xiong Glad to hear it. Thank you! Will follow up with a few other users having the same issue to confirm, but it seems likely that the issue was indeed related to the difference between the auth used by built-in SCM git and GitLens' git.

**Pull request merged**
