### PR TITLE
Renames GitCommands command to QuickWizard

### PR DESCRIPTION
**Pull request by axosoft-ramint**
Also updates telemetry source to 'quick-wizard'

Closes [#3576](https://github.com/gitkraken/vscode-gitlens/issues/3576)

### CODE REVIEW

**Comment by eamodio** [comment]
Hey @axosoft-ramint, while reviewing your PR, I'd suggest the following code changes:

👉 [**Title: Refactor quick command system for better modularity**](https://gitkraken.dev/drafts/47f3e09b-d6cd-43f4-b97f-4b8909971dd5?source=PRComment)
>While this only goes part of the way it starts paving the path to separate them more holistically

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/47f3e09b-d6cd-43f4-b97f-4b8909971dd5?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPQS1NUnVNNTc5bEREIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by axosoft-ramint** [comment]
@eamodio Committed the suggested changes after some testing to make sure nothing broke 👍🏼 thanks!

**Review by eamodio — APPROVED** [review]
Please be sure to check in with @trevor-polidore on the telemetry key changes

**Comment by axosoft-ramint** [comment]
> Please be sure to check in with @trevor-polidore on the telemetry key changes

Already got a 👍🏼 on these last week, and gave a heads-up today that they will be live in pre-release and in the next release.

**Pull request merged**
