### PR TITLE
Fixes #3116 - Fix typos in README.md and package.json

### LINKED ISSUE #3116: Typos in package.json and README.md
### Description

I found typos in package.json and README.md.
https://github.com/gitkraken/vscode-gitlens/blob/d2f8ed219fef956ac2cbf3c9d3f709440728561d/package.json#L3302

https://github.com/gitkraken/vscode-gitlens/blob/d2f8ed219fef956ac2cbf3c9d3f709440728561d/README.md?plain=1#L430

I will submit a pull request for this issue later.

### GitLens Version

14.7.0

### VS Code Version

Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

### Git Version

git version 2.42.1

## package.json
image

## README.md
image

### PR DESCRIPTION
**Pull request by yutotnh**
# Description

Fix typos in README.md and package.json.

To correct a minor typo, I have not updated CHANGELOG.md.

The issue corresponding to this pull request is #3116.

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [ ] My changes include any required corresponding changes to the documentation (including CHANGELOG.md and README.md)
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

**Review by moshahin01 — APPROVED** [review]

**Review by moshahin01 — APPROVED** [review]

**Review by moshahin01 — APPROVED** [review]

**Review by moshahin01 — APPROVED** [review]

**Review by jonspinns15 — APPROVED** [review]

**Review by d13 — APPROVED** [review]
Thanks so much for contributing!

**Comment by moshahin01** [comment]
👍

**Review by moshahin01 — COMMENTED** [review]
👍

**Review by jonspinns15 — COMMENTED** [review]
4337BC8A24CA3BDC

**Pull request merged**
