### PR TITLE
88 - Graph Styling Issue: Ref icons jump on hover

### PR DESCRIPTION
**Pull request by ericf-axosoft**
# Summary of changes
- It seems that it was happening when the Gitlens trial panel was displayed. 
- Adjusted graph icon class of Gitlens.

# Task
https://github.com/gitkraken/GitKrakenComponents/issues/88

### CODE REVIEW

**Review by axosoft-ramint — COMMENTED** [review]
I'm still seeing default icons slightly moving vertically on hover, and remote avatars sometimes warping a bit on hover:

icon jumpiness

This happens in GKC too so I'm not sure it's related to the trial banner. Still, it seems very minor and pretty much unnoticeable for me at my default zoom level (I have to zoom in several times to see it).

@eamodio Can you still see the same jumpiness you originally reported when testing this PR?

**Comment by ericf-axosoft** [comment]
@axosoft-ramint I cannot reproduce it with my changes:

https://user-images.githubusercontent.com/90025366/195867805-b1755b9d-1b06-4042-97ec-420bf56da190.mov

In my case I was be able to reproduce the problem when the panel to extend the trial was displayed. Could you please tell me the steps you have done to reproduce it?

**Comment by axosoft-ramint** [comment]
> In my case I was be able to reproduce the problem when the panel to extend the trial was displayed. Could you please tell me the steps you have done to reproduce it?

Sure.

Open GitKraken repo, then show the graph. Zoom in using Appearance -> Zoom In from the menu (I zoomed in roughly 3 times but you can try different zoom levels). Then hover the refs. It happens on some of them but not all.

**Comment by eamodio** [comment]
Running with what is on `main` (and currently published), I no longer see the jumping at all.

**Review by axosoft-ramint — APPROVED** [review]
My icons are the same with or without this PR, so I will approve in case it solves the issue you were seeing @ericf-axosoft. However, since the original issue is no longer occurring as @eamodio  stated, I recommend closing this one in case of unintended side-effects.

**Comment by d13** [comment]
@ericf-axosoft  This LGTM, looks like this branch needs a rebase.

**Comment by heatherleeann** [comment]
Merge pull request

**Comment by axosoft-ramint** [comment]
@ericf-axosoft Are we OK to close this PR?

**Comment by ericf-axosoft** [comment]
> @ericf-axosoft Are we OK to close this PR?

@axosoft-ramint If the issue is no longer reproducible, we can close it.

**Pull request closed without merging**
