### PR TITLE
branch names with special characters '<' also causes errors on the co… …mmand line like #2028

### PR DESCRIPTION
**Pull request by mcy-kylin**
# Description

branch names with special characters '<' also causes errors on the co…
…mmand line like https://github.com/gitkraken/vscode-gitlens/issues/2028

# Checklist

- [ ] I have followed the guidelines in the Contributing document
- [ ] My changes follow the coding style of this project
- [ ] My changes build without any errors or warnings
- [ ] My changes have been formatted and linted
- [ ] My changes include any required corresponding changes to the documentation
- [ ] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [ ] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

**Review by eamodio — CHANGES_REQUESTED** [review]
Thanks for the report and contribution!

The changes in src/env/node/git/git.ts aren't needed -- since they are valid branch names, just the change in `repository.ts` is required.

**Comment by mcy-kylin** [comment]
> Thanks for the report and contribution!
> 
> The changes in src/env/node/git/git.ts aren't needed -- since they are valid branch names, just the change in `repository.ts` is required.

Okay

**Comment by eamodio** [comment]
So if you want to undo that change, and just leave the `<` change, I can merge this in.

**Comment by mcy-kylin** [comment]
> So if you want to undo that change, and just leave the `<` change, I can merge this in.

sorry  i forgot to undo it

**Comment by eamodio** [comment]
Thank you for your contribution!

Thank you

**Pull request merged**
