### PR TITLE
Update trial messaging

### PR DESCRIPTION
**Pull request by sergiolms**
# Description

Solves https://github.com/gitkraken/vscode-gitlens/issues/3715

This PR changes trial messages for Pro Trial available and Trial expired states in:
- Account view
- Launchpad
- Visual File History
- Worktrees
- Cloud Patches
- Verify Email

- Changes to Graph's 3 day feature preview trial messages are addressed [here](https://github.com/gitkraken/vscode-gitlens/pull/3714).
- Changes for 7 -> 14 day trial are addressed [here](https://github.com/gitkraken/vscode-gitlens/pull/3694).

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [ ] My changes include any required corresponding changes to the documentation (including CHANGELOG.md and README.md)
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

**Review by axosoft-ramint — CHANGES_REQUESTED** [review]
I'm seeing inconsistencies between the messaging in the Figma from the linked issue and the messaging on the gates:

image

image


image

image

image

image

image

image

**Comment by justinrobots** [comment]
@sergiolms I'm still seeing the options for a 3 day preview trial on Visual File History and Worktrees. These should not exist. Are they removed in a separate PR, or should they not be showing up in this one?
image
image

**Comment by justinrobots** [comment]
@sergiolms this should be using "Get x days of GitLens Pro for free - no credit card required. Or sign in." instead of "Start your free x-day GitLens Pro trial - no credit card required. Or sign in".
image

**Comment by justinrobots** [comment]
@sergiolms this notification that pops up when users start the 3 day graph preview is still referencing "local Pro features" but should just be about the graph.

- Please change this to "You can now preview the Commit Graph on privately-hosted repos for 3 days, or start your free x-day Pro trial for full access to all GitLens Pro features."
- Change the "See Pro Features" secondary button to "Community vs. Pro" and make it link to the Community vs. Pro page like the other messages.

image

**Comment by sergiolms** [comment]
Hi @justinrobots 
> @sergiolms I'm still seeing the options for a 3 day preview trial on Visual File History and Worktrees. These should not exist. Are they removed in a separate PR, or should they not be showing up in this one? 

I was meaning to upload it in a separate PR, but I can just add a commit here if it's clearer :+1:

> @sergiolms this notification that pops up when users start the 3 day graph preview is still referencing "local Pro features" but should just be about the graph.
 
I changed this in the [Graph 3-day preview feature](https://github.com/gitkraken/vscode-gitlens/pull/3714). This notification should only appear when starting the 3 day preview for the Commit graph, since it won't be possible to start it from anywhere else, right? But if I remember correctly, we agreed on not displaying the notification since it would pop up every day, and instead we would just display the modal every 24h. Those changes are applied in the linked PR, but l'll change this notification in this PR as well just in case.

**Comment by sergiolms** [comment]
Solves https://github.com/gitkraken/vscode-gitlens/pull/3694

**Comment by sergiolms** [comment]
Changes from this PR will be included in https://github.com/gitkraken/vscode-gitlens/pull/3714

**Pull request closed without merging**
