### PR TITLE
Closes #1399 - Adds option to filter out merge commits

### LINKED ISSUE #1399: Filter out Merge Commits in Commit View
Hi there, love the product.
In our project we have a lot of merge commits, do you think it would be feasible to have a flag on the commit view to filter those?

This would basically be like `git log --no-merges`

Thanks a lot.

### PR DESCRIPTION
**Pull request by Shashank-Shastri**
# Description

- Closes #1399 - Implements feature mentioned in https://github.com/eamodio/vscode-gitlens/issues/1399.

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [ ] My changes include any required corresponding changes to the documentation
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

**Comment by jorisa** [comment]
Can we get this in by any chance? Really looking forward to this

**Comment by Shashank-Shastri** [comment]
@jorisa I'm looking forward to this as well, but we'll just have to wait for @eamodio's review.

**Comment by jorisa** [comment]
@eamodio any chance you can take a look at this?

**Comment by eamodio** [comment]
So sorry for the LONG delay and thank you for your contribution!

Thank you

**Comment by obxpete** [comment]
@eamodio Thank you!

**Pull request merged**
