### PR TITLE
Move remaining GitHub auth logic that uses vscode auth (GLVSC-589)

### PR DESCRIPTION
**Pull request by sergeibbb**
# Description

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [ ] My changes include any required corresponding changes to the documentation (including CHANGELOG.md and README.md)
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

### CODE REVIEW

**Comment by Bibek2057703** [comment]
[**`****`**](url)

**Review by axosoft-ramint — COMMENTED** [review]
@sergeibbb

One remaining functionality we wanted with cloud integrations that isn't covered yet, based on my testing:

We need to add a `provider:authentication:skip:${provider}` setting for all integrations that is flagged when a user chooses to disconnect from a provider locally, and is respected by `syncCloudIntegrations`, so that they are not automatically re-connected to the cloud integration without choosing to do so.

For example:
-I am connected to the GitLab cloud integration.
-I click "disconnect" on my GitLab remote.
-It disconnects from "GitLab", as expected.
-However, I am still connected to GitLab cloud integration on the API, so the next time GitLens does an automatic checkin or the next time I click the "cloud integrations" button and then refocus the window, `syncCloudIntegrations` will automatically reconnect me to GitLab and my remote is once again connected without my permission.
-I should explicitly choose to reconnect GitLab, either through Launchpad or a GitLab remote, or some other place, to be reconnected. `syncCloudIntegrations` should not reconnect me in this case because I chose explicitly to disconnect. Same applies with GitHub and all other providers when I disconnect manually.

**Review by axosoft-ramint — APPROVED** [review]
@sergeibbb My above comment can be addressed in follow-up and does not need to prevent this PR from merging. It is more related to general behavior of cloud integrations. I thought I would mention it here because I encountered it while testing the PR, but please feel free to write a separate issue for it.

**Comment by axosoft-ramint** [comment]
I have moved the above request into a new Jira ticket: https://gitkraken.atlassian.net/browse/GLVSC-622

Going to merge this one.

**Pull request merged**
