### PR TITLE
Melesedits

### PR DESCRIPTION
**Pull request by SpaceMerlin33**
Polished top of readme

### CODE REVIEW

**Comment by eamodio** [comment]
@SpaceMerlin33 @eatmorespinach Is this supposed to be opened still? If so, what is this?

**Comment by eatmorespinach** [comment]
@eamodio this was a rough draft branch of the readme updates between @SpaceMerlin33  and I. I then opened https://github.com/gitkraken/vscode-gitlens/pull/3712#pullrequestreview-2422181740 with @justinrobots where the official readme changes occurred. I can delete 3675 once 3712 is live.

**Comment by eamodio** [comment]
OK, let's keep anything not ready for final review/merging as a draft PR.

**Comment by d13** [comment]
@SpaceMerlin33  @eatmorespinach  Are these changes still needed?

**Pull request closed without merging**
