### PR TITLE
Fixes #2923 - TypeError: Only absolute URLs are supported

### LINKED ISSUE #2923: TypeError: Only absolute URLs are supported
Type: <b>Bug</b>

Generate Commit Message

Extension version: 14.3.0
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.59GB free)|
|Process Argv|F:\\Spreewälder Hofladen GmbH\\AmazonAPI|
|Screen Reader|no|
|VM|50%|
</details>

### PR DESCRIPTION
**Pull request by sumonst21**

### CODE REVIEW

**Comment by eamodio** [comment]
@sumonst21 Thanks -- that shouldn't be needed unless you have the `gitlens.ai.experimental.openai.url` setting in your config, but set to an empty string?

**Comment by sumonst21** [comment]
> @sumonst21 Thanks -- that shouldn't be needed unless you have the `gitlens.ai.experimental.openai.url` setting in your config, but set to an empty string?
Oh My... that is what it was, not sure when it happend, anyways, I really can't express how happy I am to have such great support from you. God Bless you @eamodio  :)
image

**Comment by circlesmiler** [comment]
> gitlens.ai.experimental.openai.url

@eamodio I experienced the same problem. I installed a complete fresh VSCode and re-installed all plugins. I tried the "Explain Commit" AI feature and it asks me for the OpenAI API token. I provided the key. Maybe at this point, an empty URL is put into the user settings?

**Comment by eamodio** [comment]
@circlesmiler I don't see how that is possible as GitLens never writes to that setting ever. Its more likely that it was sync'd to your new machine.

**Pull request closed without merging**
